name: Set Branch Protection

on:
  workflow_dispatch:

jobs:
  set-branch-protection:
    runs-on: ubuntu-latest
    steps:
      - name: Set Branch Protection
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const owner = 'gregmulvihill';
            const repo = 'orchestrate-ai';
            const branch = 'main';
            
            await github.rest.repos.updateBranchProtection({
              owner,
              repo,
              branch,
              required_status_checks: null,
              enforce_admins: true,
              required_pull_request_reviews: {
                dismissal_restrictions: {},
                dismiss_stale_reviews: true,
                require_code_owner_reviews: false,
                required_approving_review_count: 1,
              },
              restrictions: null
            });
            
            console.log(`Branch protection set for ${owner}/${repo}/${branch}`);
